# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squarecloud < Formula
  desc "Square Cloud CLI Aplication"
  homepage "https://github.com/richaardev/"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/richaardev/squarecloud-cli/releases/download/v1.1.1/squarecloud_1.1.1_darwin_arm64.tar.gz"
      sha256 "6c1cac84461ee2f9dc38ebb1a2c0c8d9cc867203aeb1bed7ad25aaeea35e3dd3"

      def install
        bin.install "squarecloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/richaardev/squarecloud-cli/releases/download/v1.1.1/squarecloud_1.1.1_darwin_amd64.tar.gz"
      sha256 "af24c052eb0f28a7904545afeee77ce7aa176300d03376bb0018fcf9b7e364a5"

      def install
        bin.install "squarecloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/richaardev/squarecloud-cli/releases/download/v1.1.1/squarecloud_1.1.1_linux_arm64.tar.gz"
      sha256 "72c530f74c5ad65198f9a2859317150129438c5c617ba3526ab27775e2b2aedb"

      def install
        bin.install "squarecloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/richaardev/squarecloud-cli/releases/download/v1.1.1/squarecloud_1.1.1_linux_amd64.tar.gz"
      sha256 "da8daff64b3ca52bf1f79a9a4b6025502bdec112cf916c14200829895a4bb78c"

      def install
        bin.install "squarecloud"
      end
    end
  end
end
